### PR TITLE
Making sure neutron-server is restarted after a PG package upgrade/downgrade

### PR DESCRIPTION
**Pull request by junaid-ali**
Ticket: [SOL-1186]
Signed-off-by: Junaid Ali junaidali@plumgrid.com

### CODE REVIEW

**Comment by junaid-ali** [comment]
This patchset will restart neutron-server even if the configs files are not changed after a PG package upgrade/downgrade

**Comment by junaid-ali** [comment]
@JaveriaK @bilalbaqar @salmankh @MQasimSarfraz @akhayam

**Comment by mqasimsarfraz** [comment]
+1, looks good.

**Comment by junaid-ali** [comment]
Thanks @MQasimSarfraz for the review

**Pull request merged**
